---
- name: check system package manager
  find:
    paths: /etc/apt/
  register: apt_state
  
- name: Update all packages
  apt:
    upgrade: dist
  become: yes
  when: apt_state.matched > 0

- name: Installl common packages
  package:
    name: "{{ common_packages}}"
    state: latest
  become: yes  
...
